version: "1"

services:
  api:
    build: .
    container_name: "peracare-api-container"
    ports:
      - "8080:8080"
    env_file:
      - .env.docker-compose

  # mongodb:
  #   image: bitnami/mongodb:latest
  #   ports:
  #     - "27017"
  #   volumes:
  #     - data:/bitnami/mongodb


volumes:
  data: